[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2021"
default-run = "run"

[[bin]]
name = "run"
path = "src/bin/run.rs"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[dependencies]
regex = "1.12.2"
